### PR TITLE
Updates PR template to include standard formatting, and emphasise automated testing

### PR DESCRIPTION
**Pull request by JakeSteam**
## Links

[Discussion last year about PR template](https://www.notion.so/seatfrog/WIP-Pull-Request-Template-2f9123e754904748aa1612f59f44c639).

## Summary 

In the PAX retro, the issue of testers not having access to testing steps was raised. Obviously all of the fields are as optional as before, and are just a guideline for typical PRs!

The template has been changed to:

1. Mention automated testing, as per @Phils0's suggestion.
2. ~~Encourage inclusion of screenshots / videos.~~
3. Include basic formatting (linear link, ~~screenshot table~~, testing steps) to avoid developer work.
4. Reminder that reviewers and testers will need useful testing steps.

## Screenshots 

| Old | New |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by JacobMillward** [comment]
The new template seems quite verbose. Do we need the screenshot section?

**Comment by JakeSteam** [comment]
> The new template seems quite verbose. Do we need the screenshot section?

@JacobMillward For apps we usually have them, but agree most repos won't. Not essential, Markdown tables can just be a pain 😉 Will remove depending on other's feedback.

Tbh if there's multiple changes where it only makes sense for apps OR backend we can use our own templates, hopefully we can get an agreeable "baseline" one at least though.

**Comment by gemery1** [comment]
At the risk of it becoming even more verbose, would adding a sub-section to the testing section that specifies which feature flags need to be active be of value (like a simple bullet point list)? I always forget about them when raising a PR so having them there would be a nice reminder. Not sure if the TOC team uses them much, but feature flags are a definite presence for Passengers repos.

**Review by wattson12 — APPROVED** [review]
Looks good to update. Happy to make changes per repo if its more noise for backend

**Comment by wattson12** [comment]
> @JacobMillward For apps we usually have them, but agree most repos won't. Not essential, Markdown tables can just be a pain 😉 Will remove depending on other's feedback.

Agreed on that: I add them via saved reply in GitHub 

image

**Comment by JakeSteam** [comment]
@gemery1 @JacobMillward @wattson12 

Have updated the proposed generic template to include *less* information, with the intention of the mobile teams using their own template with screenshots, feature flags, etc.

**Review by JacobMillward — APPROVED** [review]

**Review by wattson12 — APPROVED** [review]
Looks good, can merge and add specific templates for mobile repos

**Pull request merged**
